// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUCzwBYWBH7PCi5ZBFoemWY7EaKlmjGgA',
    appId: '1:375903203924:web:afea27fb669273723bf3c1',
    messagingSenderId: '375903203924',
    projectId: 'iot-1e0ae',
    authDomain: 'iot-1e0ae.firebaseapp.com',
    databaseURL: 'https://iot-1e0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-1e0ae.firebasestorage.app',
    measurementId: 'G-N3N8TVBJ2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBLwGksMH7wJjCCDP0KIKG54eQKAyMBs',
    appId: '1:375903203924:android:65b66edd12208edd3bf3c1',
    messagingSenderId: '375903203924',
    projectId: 'iot-1e0ae',
    databaseURL: 'https://iot-1e0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-1e0ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBONRpraPQSceicf32eHU0tHjLAHqq3hQc',
    appId: '1:375903203924:ios:4392ba84d73344063bf3c1',
    messagingSenderId: '375903203924',
    projectId: 'iot-1e0ae',
    databaseURL: 'https://iot-1e0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-1e0ae.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBONRpraPQSceicf32eHU0tHjLAHqq3hQc',
    appId: '1:375903203924:ios:4392ba84d73344063bf3c1',
    messagingSenderId: '375903203924',
    projectId: 'iot-1e0ae',
    databaseURL: 'https://iot-1e0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-1e0ae.firebasestorage.app',
    iosBundleId: 'com.example.smartClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUCzwBYWBH7PCi5ZBFoemWY7EaKlmjGgA',
    appId: '1:375903203924:web:3ec454600981a1993bf3c1',
    messagingSenderId: '375903203924',
    projectId: 'iot-1e0ae',
    authDomain: 'iot-1e0ae.firebaseapp.com',
    databaseURL: 'https://iot-1e0ae-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-1e0ae.firebasestorage.app',
    measurementId: 'G-7Q42Y8BZ51',
  );
}
